require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - "tmp/**/*"
    - "config/initializers/*"
    - "config/puma.rb"
    - "vendor/**/*"
    - spec/**/*
    - app/uploaders/*
    - "db/schema.rb"
    - "node_modules/**/*"
    - "db/migrate/*.rb"
    - "bin/*"
    - config/spring.rb
    - config/unicorn.rb
    - config/deploy.rb
    - config/deploy/production.rb
    - config/application.rb
    - config/environments/*

Rails:
  Enabled: true

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/GuardClause:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Layout/Tab:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  
Lint/SuppressedException:
  Enabled: false

