version : '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    tty: true
    stdin_open: true 
    build: .
    command: sh scripts/launch.sh
    volumes:
      - .:/my_song
    ports:
      - "3000:3000"
    links:
      - db

  server:
    build:
      context: containers/nginx
    volumes:
      - ./nginx/log:/var/log/nginx
      - public-data:/my_song/public
    ports:
      - 80:80 
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
  
